import { Inter } from 'next/font/google';
import './globals.css';
import { ThirdwebProvider } from "thirdweb/react";

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Custos Diretriz',
  description: 'Generated by create next app',
  link: <link rel="icon" href="/favicon.png" />,
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>{metadata.title}</title>
        {metadata.link}
      </head>
      <ThirdwebProvider>

      <body className={inter.fontStyles}>{children}</body>
      </ThirdwebProvider>

    </html>
  );
}
